version: "2.1"
services:
  datafingerprint:
      build: "."
      image: "gglusman/data-fingerprint"
      entrypoint: ['/bin/bash']
      tty: true
      stdin_open: true
      environment:
        DEBUG: 1
        PYTHONUNBUFFERED: 1
      volumes:
        - ./:/app
